### ISSUE TITLE
How to pass certificates to webdrivers

### ISSUE THREAD

**Issue by vbarnad** [titusfortner/webdrivers#115]
Using capaybaya and chromedriver the certificates works if i set to  
Capybara.app ="certificate location"

when i replace with webdrivers the chrome launcehs and throws 
"SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)"

How to pass certs to webdrivers

**Comment by twalpole** [comment]
Webdrivers handles the installation of the external binaries needed to interact with browser - chromedriver, geckodriver, etc.  Other than the locations of those binaries it has nothing to do with configuring other options in selenium.  That coupled with the fact that your statement about setting `Capybara.app ="certificate location"` doesn't make a lot of sense since `Capybara.app` needs to be set to a Rack app to do anything means this really isn't the right place for this question.
