### ISSUE TITLE
Unable to find MicrosoftWebDriver

### ISSUE THREAD

**Issue by anilreddy** [titusfortner/webdrivers#151]
#### Summary
Webdrivers is unable to find edge driver in the url: https://www.microsoft.com/en-us/download/details.aspx?id=48212 as the link is no longer available.

#### Debug Info
Please provide the following information for bug reports:

* Webdrivers version: 4.1.2
* Ruby version: jruby-9.2.7.0
* Operating system / CI Environment: Windows 10
* Browser and version: Microsoft Edge (Chromium) 77.0.235.17

#### Expected Behavior
To download the latest edge driver.

#### Actual Behavior
```ruby
[31m  Unable to find MicrosoftWebDriver. Please download the server from[0m
[31m  https://www.microsoft.com/en-us/download/details.aspx?id=48212 and place it somewhere on your PATH.[0m
[31m  More info at https://github.com/SeleniumHQ/selenium/wiki/MicrosoftWebDriver.[0m
[31m   (Selenium::WebDriver::Error::WebDriverError)[0m
[31m  ./features/support/hooks.rb:6:in `block in <main>'[0m
[31m  c:\jruby-9.2.7.0\bin\cucumber:23:in `<main>'[0m
    [36mGiven I am on the wb table page[0m
```

**Comment by kapoorlakshya** [comment]
@anilreddy Are you using a build from the Beta channel? The Dev and Canary builds are at version 78.x as of today.

Please provide the [debug log](https://github.com/titusfortner/webdrivers#logging) so we can see what exactly is going on here.

**Comment by anilreddy** [comment]
@kapoorlakshya am using the Microsoft Edge (Chromium) Beta (77.0.235.20) and I have added the debug log and it is not generating any log file and am getting the same error which I mentioned above. Below is my config in the hooks.rb file

```ruby
Before do
  Webdrivers.logger.level = :DEBUG
  Webdrivers::Edgedriver.required_version = '77.0.235.20'
  @browser = Watir::Browser.new :edge
  @browser.window.maximize
end
```

**Comment by kapoorlakshya** [comment]
Ah, that's because `watir` is attempting to launch the original Edge browser (EdgeHTML) and not the Chromium one.

Unfortunately, you'll not be able to use the new Edge with `watir` right now. `watir` is using Selenium v3 and you need v4 to use the new Edge browser. You'll have to wait for the next major release (in November-December I think) that supports Selenium v4.

I'm closing this issue, but please feel free to continue the discussion if you have any questions.

**Comment by kapoorlakshya** [comment]
Also, we removed support for `MicrosoftWebDriver` in v3.9.0, so you'll have to manually download it and provide it to Selenium if you want to use the original Edge browser.

**Comment by maheshmohan27** [comment]
> Ah, that's because `watir` is attempting to launch the original Edge browser (EdgeHTML) and not the Chromium one.
> 
> Unfortunately, you'll not be able to use the new Edge with `watir` right now. `watir` is using Selenium v3 and you need v4 to use the new Edge browser. You'll have to wait for the next major release (in November-December I think) that supports Selenium v4.
> 
> I'm closing this issue, but please feel free to continue the discussion if you have any questions.

@kapoorlakshya could you please confirm whether the recent watir 6.17v supports edge chromium or not. I am currently using watir 6.16v and unable to launch edge chromium.

**Comment by kapoorlakshya** [comment]
@maheshmohan27 I don't believe so because Edge (chromium) support was added in Selenium 4.0.0.alpha3 (see [changelog](https://github.com/SeleniumHQ/selenium/blob/c146621f39dbec94114835aa1f6af6a0e1fa4cd0/rb/CHANGES#L117)) and `watir` is still using 3.x in the [gemspec](https://github.com/watir/watir/blob/3ed5698f4f93bd60177318dff83f32f7b606544b/watir.gemspec#L28). You might be able to point Selenium to the Edge (chromium) binary instead of Chrome and trick it into thinking it's running Chrome, but no promises that it'll work 😄

**Comment by maheshmohan27** [comment]
> @maheshmohan27 I don't believe so because Edge (chromium) support was added in Selenium 4.0.0.alpha3 (see [changelog](https://github.com/SeleniumHQ/selenium/blob/c146621f39dbec94114835aa1f6af6a0e1fa4cd0/rb/CHANGES#L117)) and `watir` is still using 3.x in the [gemspec](https://github.com/watir/watir/blob/3ed5698f4f93bd60177318dff83f32f7b606544b/watir.gemspec#L28). You might be able to point Selenium to the Edge (chromium) binary instead of Chrome and trick it into thinking it's running Chrome, but no promises that it'll work 😄

Thank you for the response.
