### ISSUE TITLE
Is webdrivers designed to support multiple selenium versions?

### ISSUE THREAD

**Issue by luke-hill** [titusfortner/webdrivers#208]
#### Summary
Started getting failures in CI using latest webdrivers and an "old" gemfile.

```
gem 'addressable', '< 2.6'
gem 'capybara', '< 3.12'
gem 'nokogiri', '< 1.11'
gem 'selenium-webdriver', '< 3.13'
```

#### Debug Info
https://github.com/site-prism/site_prism/runs/2123477812

* Webdrivers version: Installing webdrivers 4.6.0
* Ruby version: Various
* Operating system / CI Environment: Travis
* Browser and version: Various

#### Expected Behavior
Webdrivers to run

#### Actual Behavior

Note, I don't test on Edge. So this is likely a minor bug.

```
undefined method `driver_path=' for Selenium::WebDriver::Edge::Service:Class (NoMethodError)
/home/travis/.rvm/gems/ruby-2.4.10/gems/webdrivers-4.6.0/lib/webdrivers/edgedriver.rb:114:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.10/gems/webdrivers-4.6.0/lib/webdrivers.rb:5:in `require'
/home/travis/.rvm/gems/ruby-2.4.10/gems/webdrivers-4.6.0/lib/webdrivers.rb:5:in `<top (required)>'
/home/travis/build/site-prism/site_prism/features/support/env.rb:8:in `require'
```

**Comment by luke-hill** [comment]
Update: Based on https://github.com/site-prism/site_prism/pull/93/commits/6468fc70c76b53df1dce30a4f6dcbe6ea92469d1 this proves that using the latest webdrivers won't work with old versions of selenium

**Comment by kapoorlakshya** [comment]
@luke-hill Thanks for reporting this issue. I was able to use your repo and `Gemfile.low_spec` to reproduce the error in v4.6, but not in v4.5, which tells me that the bug was introduced by [this change](https://github.com/titusfortner/webdrivers/commit/850e9107adaf4d948c430c228773298ef180eca0#diff-eb4b9e3465206641111fd932ecef8623319d551b888fd5911164ab42e5bedc03R114). I think adding this check back will fix it:

```rb
if ::Selenium::WebDriver::Service.respond_to? :driver_path=
  ::Selenium::WebDriver::Edge::Service.driver_path = proc { ::Webdrivers::Edgedriver.update }
end
```

@titusfortner Any reason to not use the above?

**Comment by titusfortner** [comment]
Selenium 3 only supports the legacy Edge HTML, which was force removed from Windows machines last month. 
Selenium 4 only supports the new Chromium Edge.
The Edge support in webdrivers has always been Chromium-only and previously required [running off of github / trunk](https://github.com/titusfortner/webdrivers/commit/850e9107adaf4d948c430c228773298ef180eca0#diff-3a6b671858fc60d511e90bdd184e68a4644100e3db05826e74738fe756cb5532L7) in order to work.

So no, there is no Edge support from webdrivers in Selenium 3, only in latest Selenium 4 beta. 
We can make that more explicit in the README if necessary.

**Comment by luke-hill** [comment]
Just catching back up to this. So the actionable bit here is advise users not to use webdrivers v4.5+ with selenium < 3.11
