### ISSUE TITLE
msedgedriver wrong version for OS being fetched

### ISSUE THREAD

**Issue by dillonbarker-te** [titusfortner/webdrivers#229]
#### Summary
- msedgedriver
- when using microsoft edge `98.0.1108.43`
- tries to fetch msedgedriver `Latest version available: 98.0.1108.50`
- network call  to`https://msedgedriver.azureedge.net//98.0.1108.50/edgedriver_mac64.zip`
- Get response: #<Net::HTTPNotFound 404 Not Found readbody=true>
- there isnt a version above for mac so it wont work

#### Debug Info
Please provide the following information for bug reports:

* Webdrivers version: 5.0.0
* Ruby version: 2.7.4
* Operating system / CI Environment: MacOS 12.1
* Browser and version: edge 98.0.1108.43

#### Expected Behavior
It should try to download the correct version of the msedgedriver for my os and browser.

#### Actual Behavior
Net::HTTPServerException: 404 "Not Found" with https://msedgedriver.azureedge.net//98.0.1108.50/edgedriver_mac64.zip

**Comment by jacob-ewald** [comment]
Getting the same error for win32. The XML coming from https://msedgedriver.azureedge.net/ does not list `98.0.1108.51` (or `.50`) as a version, despite that being the version listed in the `LATEST_STABLE` [file](https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/LATEST_STABLE).

**Comment by kapoorlakshya** [comment]
@dillonbarker-te @jacob-ewald Is this still happening? I see that `LATEST_STABLE` is now pointing to `98.0.1108.56` which does [exist](https://msedgedriver.azureedge.net/98.0.1108.56/edgedriver_mac64.zip).

**Comment by kapoorlakshya** [comment]
Either way, this is something that only Microsoft can solve because they control the downloads. The only thing webdrivers can do in this situation is allow you to [pin](https://github.com/titusfortner/webdrivers#version-pinning) to an available download version and ignore whatever `LATEST_STABLE` has. Once MS fixes the downloads, you can unpin and start using the latest.

**Comment by dillonbarker-te** [comment]
I got around it by retrying as it seemed it would attempt the correct version after trying twice. But i will check later for you whether it is happening without the retry. Thanks for the update.


Dillon Barker

**Comment by jacob-ewald** [comment]
The releases and the XML that points at them seem to be in harmony again. Instead of pinning to a version, we introduced an environment variable that is set on our build server that ignores updates for a set period of time. Once that time elapses it will try to go through the standard update logic like normal. Seemed easier to maintain when these hiccups occur since I don't have to remember to unpin anything after the issue clears up.

**Comment by kapoorlakshya** [comment]
@jacob-ewald Sounds like your env var approach is similar to the [cache time](https://github.com/titusfortner/webdrivers#caching-drivers) feature in webdrivers.

Closing this as everything seems to be working now.
