### ISSUE TITLE
Dealing with Webmock

### ISSUE THREAD

**Issue by mltsy** [titusfortner/webdrivers#4]
I'm using `webmock` in my tests and I can't figure out a good way to deal with it blocking `webdrivers`' requests.  I've tried not requiring `webmock` in the gem file, and explicitly requiring it *after* `webdrivers` in `test_helper.rb` and it still blocks the request... do you have a good method for avoiding this problem?  

Where do you normally `require 'webdrivers'` ?  Do you use `webmock`?  Is there a command I can call to make it download the drivers immediately so it doesn't get caught after webmock is initialized?

**Comment by titusfortner** [comment]
I do not use webmock, but it should let you stub only the internet calls you want?

I think it black lists by default, but you can whitelist: `https://github.com/mozilla/geckodriver/releases`, `http://chromedriver.storage.googleapis.com`

I require it in `spec_helper.rb`

**Comment by mltsy** [comment]
Well that sounds simple enough :)  Pokes a couple holes in the webmock wall, but I guess as long as you're not testing anything to do with webdrivers, it shouldn't be a problem!

I ended up just adding the webdrivers I needed to the image I was using rather than installing them as part of the test run.  But this solution certainly seems like it should work :+1:

**Comment by Crisfole** [comment]
For future viewers of this:

```
WebMock.disable_net_connect!({
  allow_localhost: true,
  allow: 'chromedriver.storage.googleapis.com'
})
```

**Comment by jrochkind** [comment]
I ran into this switching from chromedriver-helper to webdrivers. 

It is a gotcha. If the URLs that webdrivers tries to contact change in the future, of course the Webmock setup would have to be changed too. 

This is related to https://github.com/titusfortner/webdrivers/issues/29

The `allow: 'chromedriver.storage.googleapis.com'` worked. Of course if webdrivers ever changes what urls it has to contact, or contacts different URLs in different configurations (if I switch to FF instead of Chrome say?), it would have to be adjusted.
